
package clases;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://clases/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clases.Post>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostsUsuario", targetNamespace = "http://clases/", className = "clases.GetPostsUsuario")
    @ResponseWrapper(localName = "getPostsUsuarioResponse", targetNamespace = "http://clases/", className = "clases.GetPostsUsuarioResponse")
    @Action(input = "http://clases/SoapService/getPostsUsuarioRequest", output = "http://clases/SoapService/getPostsUsuarioResponse")
    public List<Post> getPostsUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearPost", targetNamespace = "http://clases/", className = "clases.CrearPost")
    @ResponseWrapper(localName = "crearPostResponse", targetNamespace = "http://clases/", className = "clases.CrearPostResponse")
    @Action(input = "http://clases/SoapService/crearPostRequest", output = "http://clases/SoapService/crearPostResponse")
    public String crearPost(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
